name: Dishant meena 

on: push

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: Find and Replace

        uses: jacobtomlinson/gha-find-replace@master

        with:

          find: "HEXOROP/Musicsanki"

          replace: "NANDAN-VAMPIRE/VAMPIRE-OP"

      - name: Create Pull Request

        uses: stefanzweifel/git-auto-commit-action@v4

        with:

          commit_message: 'Initial commit'

          commit_options: '--no-verify'

          repository: .

          commit_user_name: MickeyxD

          commit_user_email: Dishantmeena456@gmail.com
